#!/bin/bash

# This is what we normally need to do to rebuild and deploy.
# Meant as a guide - be cautious about running this, it updates prod-0.


# Revamped version with new ICA vocabs, and lod.coop URLs.
# A -dev suffix builds the development version using URLs starting with `dev.`
./build 2.1-dev
./deploy generated/2.1 dev-0:/var/www/vhosts/vocabs.solidarityeconomy.coop/www/essglobal/2.1

# Still the old V2a version using w3id.solidarityeconomy.coop URLs.
./build sea
./deploy generated/sea prod-0:/var/www/vhosts/vocabs.solidarityeconomy.coop/www/essglobal/2.1
